version: '3.1'

services:
  redis:
    image: redis:7-alpine
    restart: always
    logging:
      driver: none

  mysql:
    image: ubuntu/mysql:8.0-22.04_beta
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    command: --default-authentication-plugin=mysql_native_password
    logging:
      driver: none

  ytdl:
    image: bennythink/ytdlbot
    env_file:
      - .env
    restart: always
    volumes:
      - ./youtube-cookies.txt:/app/youtube-cookies.txt
    depends_on:
      - redis